repositories {
	mavenCentral()
}

dependencies {
	implementation project(':account-service-api')

    //Spring Actuator
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	//Spring Prometheus
	implementation 'io.micrometer:micrometer-registry-prometheus'
}

def generated = 'src/main/generated'

tasks.withType(JavaCompile) {
    options.getGeneratedSourceOutputDirectory().set(file(generated))
}

sourceSets {
    main.java.srcDirs += [ generated ]
}

clean {
    delete file(generated)
}

tasks.named('test') {
	useJUnitPlatform()
}
